-- P6-B minimal schema for SubmitAction runtime persistence (PostgreSQL/Supabase)
CREATE SCHEMA IF NOT EXISTS ${schema};

CREATE TABLE IF NOT EXISTS ${schema}.schema_version (
    version INTEGER PRIMARY KEY,
    description TEXT NOT NULL,
    applied_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ${schema}.match_state (
    match_id VARCHAR(255) PRIMARY KEY,
    payload TEXT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ${schema}.idempotency (
    idempotency_key VARCHAR(255) PRIMARY KEY,
    fingerprint TEXT NOT NULL,
    result_state TEXT NOT NULL,
    result_resolution TEXT NOT NULL,
    result_events TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ${schema}.workflow_event (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_payload TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

INSERT INTO ${schema}.schema_version (version, description)
SELECT 1, 'P6-B initial submit action runtime schema'
WHERE NOT EXISTS (SELECT 1 FROM ${schema}.schema_version WHERE version = 1);
